routes/web.php
<?php

Route::get('/', function () {
    return view('welcome');
});



Auth::routes();

Route::group(['middleware' => 'auth'], function () {
    Route::get('/home', 'HomeController@index');
    Route::resource('dishes', 'DishesController');
    Route::get('/profile', 'UsersController@profile')->name('users.profile');
    Route::post('/profile', 'UsersController@profileUpdate')->name('users.profile.update');
});

Route::group(['middleware'=>['auth', 'admin']], function(){
	Route::resource('dishes', 'DishesController');
	// Route::resource('/admin/dishes', 'DishController');
	Route::resource('/orders', 'OrdersController');
	Route::resource('/reservation', 'TableReservationController');
	Route::resource('/users', 'UsersController');
	


});



Route::get('/contacts', function () {
    return view('contacts');
});
Route::get('/reservation', function () {
    return view('/reservations/user/reservation');
});




Route::get('/shopNow', 'DishesController@user');
Route::resource('cart', 'CartController');
Route::resource('reservation', 'TableReservationController');
Route::resource('orders', 'OrderController');
Route::get('/user/orders', 'OrderController@userIndex')->name('user.orders');
Route::get('/booking', 'TableReservationController@index')->name('reservations.user.index');
Route::get('/admin/reservation', 'TableReservationController@index')->name('reservations.admin.index');

resources/views/reservations/admin/edit.blade.php
@extends('layouts.app')

@section('content')


@include('partials.errors', ['errors'=>$errors])

{!! Form::model($rez, array('route' =>array ('reservation.update', $rez->id),'method' => 'PUT')) !!}
    <div class="row">
        <div class="col-md-12 text-center"> 
             <div class="form-group">
                {{ Form::label('name', 'Name:', ['class' => 'control-label col-md-4']) }}
                <div class="col-md-6">
                    {{ Form::text('name', null, ['class'=>'form-control','required' => 'required']) }}
                </div>
            </div>
            <div class="form-group">
                {{ Form::label('phone', 'Phone:', ['class' => 'control-label col-md-4']) }}
                <div class="col-md-6">
                    {{ Form::text('phone', null,['class'=>'form-control','required' => 'required']) }}
                </div>
            </div>
            <div class="form-group">
                {{ Form::label('persons', 'Table for:', ['class' => 'control-label col-md-4']) }}
                <div class="col-md-6">
                    {{ Form::selectRange ( 'persons', 1, 10, 1, ['class'=>'form-control']) }}
                </div>
            </div>
            <div class="form-group">
                {{ Form::label('date', 'Date:', ['class' => 'control-label col-md-4']) }}
                <div class="col-md-6">
                    {{ Form::date('date', null, ['class'=>'form-control','required' => 'required']) }}
                </div>
            </div>
            <div class="form-group">
                {{ Form::label('time', 'Time:', ['class' => 'control-label col-md-4']) }}
                <div class="col-md-6">
                    {{ Form::time('time', null, ['class'=>'form-control','required' => 'required']) }}
                </div>
            </div>
            <div class="form-group">
                <div class=" col-md-6 col-md-offset-4">
                    {{ Form::submit('SAVE', array('class' => 'btn btn-primary form-control')) }}
                </div>
            </div>
        </div>
    </div>
{{ Form::close() }}

@endsection('content')

resources/views/reservations/admin/index.blade.php
@extends('layouts.app')

@section('content')



<table class="table table-striped table-bordered">
   <thead>
    <tr>
        <td>Name</td>
        <td>Phone</td>
        <td>Persons</td>
        <td>Date</td>
        <td>Time</td>
        <td>Actions</td>
    </tr>
	</thead>
	<tbody>
	    @foreach($rez as $rezerv)
	    <tr>
	        <td>{{$rezerv->name}}</td>
	        <td>{{$rezerv->phone}}</td>
	        <td>{{$rezerv->persons}}</td>
	        <td>{{$rezerv->date}}</td>
	        <td>{{$rezerv->time}}</td> 
	        <td><a class="btn btn-small btn-info" href="{{ route('reservation.edit', $rezerv->id)}}">Edit</a>
		    {!! Form::open(['route' => ['reservation.destroy', $rezerv->id], 'method' => 'DELETE']) !!}
		    {!! Form::submit('Delete', array('class' => 'btn btn-warning')) !!}
		    {!! Form::close() !!} </td>
	    @endforeach
	</tbody>
</table>

@endsection('content')