routes/web.php
<?php

Route::get('/', function () {
    return view('welcome');
});



Auth::routes();

Route::group(['middleware' => 'auth'], function () {
    Route::get('/home', 'HomeController@index');
    Route::resource('dishes', 'DishesController');
    Route::get('/profile', 'UsersController@profile')->name('users.profile');
    Route::post('/profile', 'UsersController@profileUpdate')->name('users.profile.update');
});

Route::group(['middleware'=>['auth', 'admin']], function(){
	Route::resource('dishes', 'DishesController');
	// Route::resource('/admin/dishes', 'DishController');
	Route::resource('/orders', 'OrdersController');
	Route::resource('/reservation', 'TableReservationController');
	Route::resource('/users', 'UsersController');
	


});



Route::get('/contacts', function () {
    return view('contacts');
});
Route::get('/reservation', function () {
    return view('/reservations/user/reservation');
});




Route::get('/shopNow', 'DishesController@user');
Route::resource('cart', 'CartController');
Route::resource('reservation', 'TableReservationController');
Route::resource('orders', 'OrderController');
Route::get('/user/orders', 'OrderController@userIndex')->name('user.orders');
Route::get('/booking', 'TableReservationController@index')->name('reservations.user.index');
Route::get('/admin/reservation', 'TableReservationController@index')->name('reservations.admin.index');

resources/views/dishesCRUD/create.blade.php
@extends('layouts.app')


@section('content')

@include('partials.errors', ['errors'=>$errors])



    {!! Form::open([
        'route' => 'dishes.store',
        'method' => 'POST',
        'files'=>true
    ]) !!}

    <div class="form-group">
        {{ Form::label('title', 'Title:') }}
        {{ Form::text('title', null, ['required' => 'required']) }}
    </div>

    <div class="form-group">
        {{ Form::label('photo', 'Photo:') }}
        {{ Form::file('photo' ) }}

    </div>

    <div class="form-group">
        {{Form::label('description', 'Description:', ['class' => 'control-label']) }}
        {{ Form::textarea('description', null, ['class' => 'form-control']) }}
    </div>

    <div class="form-group">
        {{ Form::label('price', 'Price:') }}
        {{ Form::text('price', null, ['required' => 'required']) }}
    </div>

    {{ Form::submit('Create', array('class' => 'btn btn-primary')) }}
    {{ Form::close() }}

@endsection

resources/views/dishesCRUD/delete.blade.php
{!! Form::open(['url' => $url, 'method' => 'DELETE']) !!}
{!! Form::submit('Delete', array('class' => 'btn btn-warning')) !!}
{!! Form::close() !!}

resources/views/dishesCRUD/edit.blade.php
@extends('layouts.app')


@section('content')



@include('partials.errors', ['errors'=>$errors])


{!! Form::model($dishes, array('route' =>array ('dishes.update', $dishes->id),'method' => 'PUT', 'files'=>true)) !!}
    <div class="row">
        <div class="col-md-12 text-center"> 
            <table class="table table-bordered">
                <tr>
                    <td><div class="form-group">
                        {{ Form::label('photo', 'Photo:') }}
                        <img class="img-responsive" width="100" height="100" alt="dish image" src="{{$dishes->getPhotoUrl() }}" >
                        {{ Form::file('photo' ) }}
                    </div></td>

                    <td><div class="form-group">
                        {{ Form::label('title', 'Title:') }}
                        {{ Form::text('title', null, ['required' => 'required']) }}
                    </div></td>

                    <td><div class="form-group">
                        {{Form::label('description', 'Description:', ['class' => 'control-label']) }}
                        {{ Form::textarea('description', null, ['class' => 'form-control']) }}
                    </div></td>

                    <td><div class="form-group">
                        {{ Form::label('price', 'Price:') }}
                        {{ Form::text('price', null, ['required' => 'required']) }}
                    </div></td>

                    <td><div class="form-group">
                        {{ Form::submit('Update', array('class' => 'btn btn-primary')) }}
                        {{ Form::close() }}
                        </div></td>
                </tr>
            </table>
        </div>
    </div>
@endsection

resources/views/dishesCRUD/index.blade.php
@extends('layouts.app')

@section('content')



<table class="table table-bordered">
    <thead>
        <tr>
            <td>ID</td>
            <td>Title</td>
            <td>Photo</td>
            <td>Description</td>
            <td>Price Neto</td>
            <td>Sale price</td>
            <td>Action</td>
        </tr>
    </thead>
    <tbody>
        @foreach($dishes as $dish)
            <tr>
                <td>{{ $dish->id }}</td>
                <td>{{ $dish->title }}</td>
                <td><img class="img-responsive" width="100" height="100" alt="dish image" src="{{$dish->getPhotoUrl() }}" ></td>
                <td>{!!$dish->description !!}</td>
                <td>{{ $dish->price }}</td>
                <td>{!!$dish->getSalePrice()!!}</td>
            {{--<td>{{ $dish->Quantity }}</td>--}}
                <td><a class="btn btn-small btn-info" href="{{ URL::to('dishes/' . $dish->id . '/edit') }}">Edit</a>
                    {!! Form::open(['route' => ['dishes.destroy', $dish->id], 'method' => 'DELETE']) !!}
                    {!! Form::submit('Delete', array('class' => 'btn btn-warning')) !!}
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
    </tbody>
</table>

@endsection

resources/views/dishesCRUD/orders.blade.php
@extends('layouts.app')

@section('content')

<table class="table table-bordered">
    <tr>
        <th>Name</th>
        <th>User ID</th>
        <th>Date</th>
        <th>Total</th>
        <th>Order id</th>
        <th>Products</th>
        <th>Action</th>
    </tr>
    @foreach($orders as $order)
        <tr>
            <td>
                @if($order->user)
                    {{ $order->user->getFullName() }}
                @endif
            </td> 
            <td>{{ $order->user_id }}</td>  
            <td>{{ $order->created_at }}</td> 
            <td>{{ $order->total }}</td>    
            <td>{{ $order->id }}</td>
            <td>
                <ul>
                    @foreach ($order->dishes as $product)
                        <li>
                            {{$product->title }} x 
                            {{$product->pivot->quantity}} x
                            {{$product->pivot->price}} &euro;,
                            {{$product->pivot->price*$product->pivot->quantity}} &euro;
                        </li>
                    @endforeach
                </ul>
            </td>
            <td>
                {!! Form::open(['route' => ['orders.destroy', $order->id], 'method' => 'DELETE'])!!}
                {!! Form::submit('DELETE', ['class'=>'btn btn-warning']) !!}
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
</table>
<div class="row">
    <div class="col-md-3 col-md-offset-4 btn btn-info">
        Totals: {{ $order->sum('total')}}
    </div>
</div>


@endsection

resources/views/dishesCRUD/usercreate.blade.php
@extends('layouts.app')

@section('content')


@include('partials.errors', ['errors'=>$errors])
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Register</div>

                <div class="panel-body">
                    <form class="form-horizontal" role="form">
                    @if (session('message'))
                        <div class="alert alert-success">
                            {{session('message')}}
                        </div>
                    @endif
                    {!! Form::open(['route' => 'users.store','method' => 'POST']) !!}
                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">Name</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control" name="name" value="{{ old('name') }}" required autofocus>

                                @if ($errors->has('name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('surname') ? ' has-error' : '' }}">
                            <label for="surname" class="col-md-4 control-label">Surname</label>

                            <div class="col-md-6">
                                <input id="surname" type="text" class="form-control" name="surname" value="{{ old('surname') }}" required autofocus>

                                @if ($errors->has('surname'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('surname') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('birthdate') ? ' has-error' : '' }}">
                            <label for="birthdate" class="col-md-4 control-label">Birthdate</label>

                            <div class="col-md-6">
                                <input id="birthdate" type="text" class="form-control" name="birthdate" value="{{ old('birthdate') }}" required autofocus>

                                @if ($errors->has('birthdate'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('birthdate') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('phone') ? ' has-error' : '' }}">
                            <label for="phone" class="col-md-4 control-label">Phone number</label>

                            <div class="col-md-6">
                                <input id="phone" type="text" class="form-control" name="phone" value="{{ old('phone') }}" required autofocus>

                                @if ($errors->has('phone'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('phone') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('address') ? ' has-error' : '' }}">
                            <label for="address" class="col-md-4 control-label">Address</label>

                            <div class="col-md-6">
                                <input id="address" type="text" class="form-control" name="address" value="{{ old('address') }}" required autofocus>

                                @if ($errors->has('address'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('address') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('city') ? ' has-error' : '' }}">
                            <label for="city" class="col-md-4 control-label">City</label>

                            <div class="col-md-6">
                                <input id="city" type="text" class="form-control" name="city" value="{{ old('city') }}" required autofocus>

                                @if ($errors->has('city'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('city') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('zip') ? ' has-error' : '' }}">
                            <label for="zip" class="col-md-4 control-label">Zip code</label>

                            <div class="col-md-6">
                                <input id="zip" type="text" class="form-control" name="zip" value="{{ old('zip') }}" required autofocus>

                                @if ($errors->has('zip'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('zip') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('country') ? ' has-error' : '' }}">
                            <label for="country" class="col-md-4 control-label">Country</label>

                            <div class="col-md-6">
                                <input id="country" type="text" class="form-control" name="country" value="{{ old('country') }}" required autofocus>
                                {{--<select class="input-medium bfh-countries" data-country="US"></select>--}}
                                @if ($errors->has('country'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('country') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>


                        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                            <label for="email" class="col-md-4 control-label">E-Mail Address</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control" name="email" value="{{ old('email') }}" required>

                                @if ($errors->has('email'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                            <label for="password" class="col-md-4 control-label">Password</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control" name="password" required>

                                @if ($errors->has('password'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="password-confirm" class="col-md-4 control-label">Confirm Password</label>

                            <div class="col-md-6">
                                <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                {{ Form::submit('Create', array('class' => 'btn btn-primary')) }}
                            </div>
                        </div>
                        {!! Form::close() !!}
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/dishesCRUD/userprofile.blade.php
@extends('layouts.app')

@section('content')

@include('partials.errors', ['errors'=>$errors])

<style type="text/css">
    .table-profile td{
        display: block;
    }

</style>

{!! Form::model($users, array('route' =>array ('users.profile.update', $users->id),'method' => 'POST')) !!}
    <div class="row">
        <div class="col-md-12 text-center"> 
            <table class="table table-bordered table-profile">
                <tr>
                    <td><div class="form-group">
                        {{ Form::label('name', 'Name:') }}
                        {{ Form::text('name', null, ['required' => 'required']) }}
                    </div></td>

                    <td><div class="form-group">
                        {{ Form::label('surname', 'Surname:') }}
                        {{ Form::text('surname', null, ['required' => 'required']) }}
                    </div></td>

                    <td><div class="form-group">
                        {{ Form::label('email', 'Email:') }}
                        {{ Form::text('email', null, ['required' => 'required']) }}
                    </div></td>                  

                    <td><div class="form-group">
                        {{ Form::label('phone', 'Phone:') }}
                        {{ Form::text('phone', null, ['required' => 'required']) }}
                    </div></td>     

                    <td><div class="form-group">
                        {{ Form::label('address', 'Address:') }}
                        {{ Form::text('address', null, ['required' => 'required']) }}
                    </div></td>     

                    <td><div class="form-group">
                        {{ Form::label('city', 'City:') }}
                        {{ Form::text('city', null, ['required' => 'required']) }}
                    </div></td>

                    <td><div class="form-group">
                        {{ Form::label('zip', 'Zip:') }}
                        {{ Form::text('zip', null, ['required' => 'required']) }}
                    </div></td> 

                    <td><div class="form-group">
                        {{ Form::label('country', 'Country:') }}
                        {{ Form::text('country', null, ['required' => 'required']) }}
                    </div></td> 

                    <td><div class="form-group">
                        {{ Form::label('birthdate', 'Birthdate:') }}
                        {{ Form::text('birthdate', null, ['required' => 'required']) }}
                    </div></td> 
                

                    <td><div class="form-group">
                        {{ Form::submit('Update', array('class' => 'btn btn-primary')) }}
                    </div></td>
                </tr>
            </table>
        </div>
    </div>
{{ Form::close() }}
@endsection

resources/views/dishesCRUD/userregister.blade.php
@extends('layouts.app')

@section('content')

@include('partials.admin_navbar')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Register</div>
                <div class="panel-body">
                    <form class="form-horizontal" role="form" method="POST" action="{{ url('/register') }}">
                        {{ csrf_field() }}

                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">Name</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control" name="name" value="{{ old('name') }}" required autofocus>

                                @if ($errors->has('name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('surname') ? ' has-error' : '' }}">
                            <label for="surname" class="col-md-4 control-label">Surname</label>

                            <div class="col-md-6">
                                <input id="surname" type="text" class="form-control" name="surname" value="{{ old('surname') }}" required autofocus>

                                @if ($errors->has('surname'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('surname') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('birthdate') ? ' has-error' : '' }}">
                            <label for="birthdate" class="col-md-4 control-label">Birthdate</label>

                            <div class="col-md-6">
                                <input id="birthdate" type="text" class="form-control" name="birthdate" value="{{ old('birthdate') }}" required autofocus>

                                @if ($errors->has('birthdate'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('birthdate') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('phone') ? ' has-error' : '' }}">
                            <label for="phone" class="col-md-4 control-label">Phone number</label>

                            <div class="col-md-6">
                                <input id="phone" type="text" class="form-control" name="phone" value="{{ old('phone') }}" required autofocus>

                                @if ($errors->has('phone'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('phone') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('address') ? ' has-error' : '' }}">
                            <label for="address" class="col-md-4 control-label">Address</label>

                            <div class="col-md-6">
                                <input id="address" type="text" class="form-control" name="address" value="{{ old('address') }}" required autofocus>

                                @if ($errors->has('address'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('address') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('city') ? ' has-error' : '' }}">
                            <label for="city" class="col-md-4 control-label">City</label>

                            <div class="col-md-6">
                                <input id="city" type="text" class="form-control" name="city" value="{{ old('city') }}" required autofocus>

                                @if ($errors->has('city'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('city') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('zip') ? ' has-error' : '' }}">
                            <label for="zip" class="col-md-4 control-label">Zip code</label>

                            <div class="col-md-6">
                                <input id="zip" type="text" class="form-control" name="zip" value="{{ old('zip') }}" required autofocus>

                                @if ($errors->has('zip'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('zip') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('country') ? ' has-error' : '' }}">
                            <label for="country" class="col-md-4 control-label">Country</label>

                            <div class="col-md-6">
                                <input id="country" type="text" class="form-control" name="country" value="{{ old('country') }}" required autofocus>
                                {{--<select class="input-medium bfh-countries" data-country="US"></select>--}}
                                @if ($errors->has('country'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('country') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>


                        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                            <label for="email" class="col-md-4 control-label">E-Mail Address</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control" name="email" value="{{ old('email') }}" required>

                                @if ($errors->has('email'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                            <label for="password" class="col-md-4 control-label">Password</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control" name="password" required>

                                @if ($errors->has('password'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="password-confirm" class="col-md-4 control-label">Confirm Password</label>

                            <div class="col-md-6">
                                <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Register
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/dishesCRUD/users.blade.php
@extends('layouts.app')

@section('content')



<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Surname</th>
        <th>Email</th>
        <th>Phone</th>
        <th>Address</th>
        <th>City</th>
        <th>Zip</th>
        <th>Country</th>
        <th>Birthdate</th>
        <th>is admin</th>
        <th>Action</th>
    </tr>
    @foreach($users as $user)
        <tr>
            <td>{{ $user->id}}</td> 
            <td>{{ $user->name}}</td>  
            <td>{{ $user->surname}}</td>    
            <td>{{ $user->email}}</td>
            <td>{{ $user->phone}}</td>
            <td>{{ $user->address}}</td>
            <td>{{ $user->city}}</td>
            <td>{{ $user->zip}}</td>
            <td>{{ $user->country}}</td>
            <td>{{ $user->birthdate}}</td> 
            <td> 
                @if ($user->isAdmin())
                   is admin
                @else
                    not admin
                @endif
            </td> 
                @if ($user->id != Auth::user()->id)
                    <td>
                        <a class="btn btn-small btn-info" href="{{route('users.edit', $user->id)}}">Edit</a>
                        {!! Form::open(['route' => ['users.destroy', $user->id], 'method' => 'DELETE'])!!}
                        {!! Form::submit('DELETE', ['class'=>'btn btn-warning']) !!}
                        {!! Form::close() !!}
                    </td>
                @else
                <td> 
                    <a class="btn btn-small btn-info" href="{{route('users.edit', $user->id)}}">Edit</a>
                </td>
                @endif
        </tr>
    @endforeach
</table>

@endsection